language: java
jdk:
  - openjdk7
  - oraclejdk7
script: ./gradlew -q jar oneJar distZip
after_script:
  - test -f ./build/libs/PackageManager.jar
  - test -f ./build/libs/PackageManager-standalone.jar
  - test -f ./build/distributions/PackageManager.zip
install: /bin/true
notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email: false
